### ISSUE TITLE
Question about the demonstration

### ISSUE THREAD

**Issue by JisuHann** [ankile/furniture-diffusion#27]
Hello Ankile. 
I am impressed by your work. I have one question regarding the dataset.
I wonder there are many demonstrations at the benchmark, but why do you guys collected your own demonstrations. Is there any specific reason? 

I am asking because I was quite confused that the results from the imitation learning FurnitureBench benchmark paper is quite different from yours. To be specific, your paper Table VIII results show 58% success rate in ResNet, but on FurnitureBench Figure 8 shows almost around 0% success rate even with 100 demos. Could you explain how the performance gap exist? Is there any other technique or specific protocol to generate dataset?

Thank you!

**Comment by ankile** [comment]
Hi Jisu,

Thank you for your comment—I responded to your email. However, I will share my response here as well in case anyone wonders the same thing.

> I noticed that there are several demonstrations available in the FurnitureBench benchmark, but your team opted to collect your own demonstrations. Could you share if there was a specific reason for this decision?

Yeah, so the FurnitureBench team released two demos (as far as I'm aware): Teleoperation demos in the real world and scripted demonstrations in the simulator. We focused mainly on the simulator, so only those demos were relevant. However, we wanted a source of demos that was more generally available, and the scripted demos they provided were, at the time, only for the `one_leg` task. Therefore, we decided to use a SpaceMouse to teleop all the demos for all the tasks ourselves.

In [later work](https://arxiv.org/pdf/2407.16677), we also switched to using a different low-level controller (they use OSC but we switched to a DiffIK controller), meaning that the data was not compatible. Finally, when we deployed policies in the real world, we also collected our demos because of the controller difference and the need for data collected in the same environment we wanted to deploy to.

> Could you help clarify how such a performance gap exists? Are there any unique techniques or protocols used to generate the dataset that might explain this difference?

Yeah, what we found to be the crucial difference is to use big enough models and action chunking. I.e., the way we generate the dataset doesn't matter too much. For example, we experimented very early using data generated by the scripted policy from FurnitureBench, which is easier to learn from than the human demos we used. In particular, when we compared using a big MLP that predicts only the next action with one that predicts a chunk of future actions (e.g., 8), the first got 0% success rate while the second got much better. Finally, we also used a diffusion model, which helped improve performance.
